### ISSUE TITLE
Bug: No notification sound in CPR / v11

### ISSUE THREAD

**Issue by Zoestra** [TaureHorn/FoundryVTT_ChatConsole#81]
Version 
ChatConsole: 1.9.0
Foundry: V11 stable build 315
Cyberpunk Red - CORE: v0.8.8.2

When a message is sent in a chat console, no sound is played for the other players. below is the error which appears in the console. This error still appears when ChatConsole is the only module enabled
<img width="727" height="605" alt="Image" src="https://github.com/user-attachments/assets/5cb44d30-625a-41f5-b8e1-be93340838ed" />

here is the config for the console in question, a sound is loaded, and notifications are not muted
<img width="348" height="983" alt="Image" src="https://github.com/user-attachments/assets/a75397b7-6ddd-4266-9680-1d1ac84a5ff4" />

**Comment by TaureHorn** [comment]
Fixed by #82. Please upgrade to v1.9.1

**Comment by katgro99** [comment]
Hi. 
I have the newest version and I still cannot get any notification sounds. I have tried to toggle between " ", "interface", "music" and so on, in the 'Notificaton volume control context' setting but to no avail.

**Comment by TaureHorn** [comment]
What version of Foundry are you on and what system & version are you using.

Also, if there are any relevant errors in the browser console, please post the details.

**Comment by katgro99** [comment]
I use FoundryVTT 13 and the system is Blade Runner RPG v. 14.0.0.

I don't know if these errors are connected to the Module but this is what my console looks like after I posted a message in a console-chat

<img width="516" height="575" alt="Image" src="https://github.com/user-attachments/assets/696383bb-d0f9-43e6-89bf-0a9cd476b6e2" />

**Comment by TaureHorn** [comment]
The above screenshot shows warnings (in yellow) for features that would be changing in the future. For the error (in red) there's not enough information tell what truly caused the error, but I would doubt it was caused by this module.

I've tested on Foundry v13.345 and Blade Runner RPG v .14.0.0 and v14.0.1 and cannot recreate a lack of notification sounds, and have produced no errors in the browser console. 

Unless you have more information about your environment I'm not sure how else I can be of assistance.
